engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  scss-lint:
    enabled: true
  shellcheck:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
ratings:
  paths:
  - "**.rb"
  - "**.js"
  - "**.css"
  - "**.scss"
  - "**.sh"
  - "templates/**"
exclude_paths:
- "app/public/tinymce/**/*"
- "app/public/upndown.bundle.js"
- "app/public/marked.js"
