options:
  layouts: !basenames "_layouts/"

hidden_paths:
  - .*
  - Makefile

filename_frontmatter:
  "_posts/*":
    - key: date
      strptime: '%Y-%m-%d'
    - match: '-'
    - key: title
      match: '[^\.]+'
      format: slugify
